EXTERNAL ChangeSceneEnfermeria()
->main
=== main ===
...
Mr. Danger: Que tanto miras...
Mr. Danger: Se ve que tienes buen ojo para el peligro
...
Mr. Danger: Yo...
Mr. Danger: Soy el peligro...
...
Mr. Danger: Que?
Mr. Danger: No me crees?
Mr. Danger: Ahora vas a ver
~ChangeSceneEnfermeria()
...
->END